name: Continuous Integration (CI)

on:
  push:
    paths:
      - 'server/**'
      - 'client/**'
  pull_request:
    branches: [ "main", "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: server/yarn.lock

      - name: Installer les dépendances du Serveur
        run: |
          cd server
          yarn install

      - name: Lancer les tests unitaires
        run: |
          cd server
          yarn test

  build-images:
    needs: run-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connexion à GitHub Packages (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compiler et Pousser l'image du Serveur (Back)
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true 
          tags: ghcr.io/${{ github.repository }}/mfp-server:main 

      - name: Compiler et Pousser l'image du Client (Front)
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ github.repository }}/mfp-client:main